name: cacheSet

# Controls when the action will run.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: cacheSet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp > /dev/null --quiet
          haxelib install hxcpp-debug-server
          haxelib install lime 7.9.0
          haxelib install openfl 9.2.0
          haxelib install flixel 5.5.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 3.0.2
          haxelib install tjson 1.4.0
          haxelib install hxCodec 2.6.0
          haxelib install SScript 8.1.6
          haxelib install hscript 2.5.0
          haxelib install hxCodec 2.6.0
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc
          haxelib git flxanimate https://github.com/beihu235/flxanimate
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools
          haxelib git extension-orientation https://github.com/HaxeExtension/extension-orientation.git
          haxelib git androiddialogs https://github.com/beihu235/AndroidDialogs
          haxelib git devicelanguage https://github.com/beihu235/devicelanguage
          haxelib list         

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -${{ matrix.arch }}
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni


      - name: Save Current Cache
        id: cache-release-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build

      
        